//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MarketPlace.Resources.Views.Home {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Index {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Index() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("MarketPlace.Resources.Views.Home.Index", typeof(Index).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Rules for publishing ads.
        /// </summary>
        public static string Ads_rules {
            get {
                return ResourceManager.GetString("Ads_rules", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to choice.
        /// </summary>
        public static string Choice {
            get {
                return ResourceManager.GetString("Choice", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Find out how to earn more with MP.
        /// </summary>
        public static string Earn_more {
            get {
                return ResourceManager.GetString("Earn_more", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Explore.
        /// </summary>
        public static string Explore {
            get {
                return ResourceManager.GetString("Explore", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to MP for business.
        /// </summary>
        public static string For_business {
            get {
                return ResourceManager.GetString("For_business", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Get Started.
        /// </summary>
        public static string Get_Started {
            get {
                return ResourceManager.GetString("Get_Started", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You already have an account.
        /// </summary>
        public static string Have_account {
            get {
                return ResourceManager.GetString("Have_account", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Any ideas for collaboration? Schedule a call to learn more.
        /// </summary>
        public static string Ideas {
            get {
                return ResourceManager.GetString("Ideas", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Join Our Marketplace.
        /// </summary>
        public static string Join {
            get {
                return ResourceManager.GetString("Join", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Login In.
        /// </summary>
        public static string Login {
            get {
                return ResourceManager.GetString("Login", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Make your.
        /// </summary>
        public static string Make_your {
            get {
                return ResourceManager.GetString("Make_your", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to See what makes us different.
        /// </summary>
        public static string Makes_Different {
            get {
                return ResourceManager.GetString("Makes_Different", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Paid services.
        /// </summary>
        public static string Paid_services {
            get {
                return ResourceManager.GetString("Paid_services", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Here we have collected all the reasons - why an ad may be removed or not passed moderation.
        /// </summary>
        public static string Reasons {
            get {
                return ResourceManager.GetString("Reasons", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Schedule Call.
        /// </summary>
        public static string Schedule_Call {
            get {
                return ResourceManager.GetString("Schedule_Call", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sign Up.
        /// </summary>
        public static string Sign_Up {
            get {
                return ResourceManager.GetString("Sign_Up", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sign Up Today.
        /// </summary>
        public static string Sign_Up_Today {
            get {
                return ResourceManager.GetString("Sign_Up_Today", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Is something not working? Then this section is for you..
        /// </summary>
        public static string Smth_wrong {
            get {
                return ResourceManager.GetString("Smth_wrong", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Customer Support Center.
        /// </summary>
        public static string Support_Center {
            get {
                return ResourceManager.GetString("Support_Center", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Technical Issues.
        /// </summary>
        public static string Technical_Issues {
            get {
                return ResourceManager.GetString("Technical_Issues", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Types and cost of services, how to buy.
        /// </summary>
        public static string Types_of_services {
            get {
                return ResourceManager.GetString("Types_of_services", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unlimited Possibilities.
        /// </summary>
        public static string Unlimited_Possibilities {
            get {
                return ResourceManager.GetString("Unlimited_Possibilities", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to We find what you need.
        /// </summary>
        public static string We_find {
            get {
                return ResourceManager.GetString("We_find", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to What do we do?.
        /// </summary>
        public static string What_do_we_do {
            get {
                return ResourceManager.GetString("What_do_we_do", resourceCulture);
            }
        }
    }
}
